# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
# https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg
version: '3.6'

services:

  bd-redis:
    build: ./better-dating-cache
    image: skivol/better-dating-cache:latest
    container_name: "bd-prod-redis"
    volumes:
      - better-dating-cache-volume:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 150M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
        window: 120s

  bd-postgres:
    build: ./better-dating-database
    image: skivol/better-dating-database:latest
    container_name: "bd-prod-postgres"
    volumes:
      - better-dating-data-volume:/pgdata
      - better-dating-postgres-shm-volume:/dev/shm
    environment:
      POSTGRES_DB: "${BD_DB:?No BD_DB (database name) specified}"
      POSTGRES_USER: "${BD_DB_USER:?No BD_DB_USER (database user name) specified}"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
      PGDATA: /pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 120M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
        window: 120s
    secrets:
      - db_password

  bd-backend:
    build: ./better-dating-backend
    image: skivol/better-dating-backend:latest
    container_name: "bd-prod-backend"
    environment:
      DB_USER: "${BD_DB_USER}"
      DB_PASSWORD_FILE: "/run/secrets/db_password"
      DB_HOST: "better-dating_bd-postgres"
      DB_NAME: "${BD_DB}"
      MAIL_USER: "${BD_MAIL_USER}"
      MAIL_PASSWORD_FILE: "/run/secrets/mail_password"
      FACEBOOK_CLIENT_ID: "${FACEBOOK_CLIENT_ID}"
      FACEBOOK_CLIENT_SECRET: "${FACEBOOK_CLIENT_SECRET}"
      VK_CLIENT_ID: "${VK_CLIENT_ID}"
      VK_CLIENT_SECRET: "${VK_CLIENT_SECRET}"
    depends_on:
      - bd-postgres
    volumes:
      - better-dating-backend-logs-volume:/logs
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 250M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 2
        window: 120s
    secrets:
      - db_password
      - mail_password
    # https://docs.docker.com/compose/compose-file/#healthcheck
    # https://stackoverflow.com/questions/47520941/healthcheck-dockerfile-vs-docker-compose-yml

  bd-frontend:
    build: ./better-dating-frontend
    image: skivol/better-dating-ui:latest
    container_name: "bd-prod-frontend"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          cpus: '0.25'
          memory: 150M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 2
        window: 120s

  bd-reverse-proxy:
    build: ./better-dating-proxy
    image: skivol/better-dating-proxy:latest
    container_name: "bd-prod-reverse-proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - better-dating-reverse-proxy-logs-volume:/logs
    depends_on:
      - bd-backend
      - bd-frontend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.15'
          memory: 20M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 2
        window: 120s
    secrets:
      - source: ssl_certificate
        # https://ru.wikipedia.org/wiki/Chmod
        mode: 0644
      - source: ssl_certificate_key
        mode: 0600
      - source: dhparam
        mode: 0644

volumes:
  better-dating-cache-volume:
  better-dating-data-volume:
  better-dating-postgres-shm-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=256m"
  better-dating-reverse-proxy-logs-volume:
  better-dating-backend-logs-volume:

secrets:
  ssl_certificate:
    external: true
  ssl_certificate_key:
    external: true
  dhparam:
    external: true
  db_password:
    external: true
  mail_password:
    external: true

networks:
  default:
    driver: overlay
    attachable: true
