spring:
  main:
    banner-mode: "off"
  flyway:
    connect-retries: 30
  mail:
    protocol: smtp
    host: smtp.i.ua
    port: 465
    properties:
      mail:
        # https://stackoverflow.com/questions/22531062/log-javamailsenderimpl
        # debug: true
        smtp:
          connectiontimeout: 5000
          timeout: 15000
          writetimeout: 15000
          auth: true
          # https://stackoverflow.com/questions/26548059/sending-email-with-ssl-using-javax-mail
          ssl:
            enable: true
  session:
    # 30 days
    timeout: 2592000
    store-type: redis
#    redis:
#      namespace: "spring:session"
# TODO remove redis config because of "not binded" exception ??

logging:
  file: ./logs/better-dating-java.log

---
spring:
  profiles: production
server:
  netty:
    accesslog: /logs/better-dating_backend_access_log.log
logging:
  file: /logs/better-dating_backend_java.log

---
spring:
  profiles: development | test
datasource:
  url: r2dbc:postgresql://localhost/postgres
---
spring:
  profiles: test
password-files:
  db: password.txt
  mail: password.txt
datasource:
  username: postgres
