<#import "/common/parts.ftlh" as common>
<#-- https://github.com/usecanvas/email-templates/blob/master/templates/verify-email.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <#include "/common/head.ftlh">
    <@common.body>
        <h1>Подтвердите новый почтовый адрес</h1>
        <p>Вы недавно поменяли почтовый адрес в профиле на сайте "смотрины.укр / смотрины.рус". Нажмите на ссылку для подтверждения, что это правильный адрес.</p>
    </@common.body>
</html>
